version: "3.9"

services:
  
  #API
  api:
    image: "dir-api:v1"
    restart: unless-stopped

    command: sh -c "poetry run python /api/dir_api.py"

    # Debug tty connection
    #stdin_open: true
    #tty: true

    build:
      context: ./Backend

    networks:
      - backend

    depends_on:
      db:
        condition: service_started

    environment:
      - API_DB_CONNECTION_STRING=postgresql+asyncpg://${APP_DB_USERNAME}:${APP_DB_PASSWORD}@db:5432/${APP_DB_DBNAME}
      - APP_CONFIG=${OPERATION_MODE}
      - API_DB_MAX_CONNECTIONS=${API_DB_MAX_CONNECTIONS}
      - API_DB_POOL_RECYCLE=${API_DB_POOL_RECYCLE}
      - API_DB_MAX_OVERFLOW=${API_DB_MAX_OVERFLOW}
      - API_DB_POOL_TIMEOUT=${API_DB_POOL_TIMEOUT}
      - API_URL_PREFIX=${API_URL_PREFIX}


  # DB
  db:
    image: postgres:15.1
    restart: unless-stopped

    # Debug tty connection
    #stdin_open: true
    #tty: true
    
    networks:
      - backend

    environment:
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD} 
      - POSTGRES_USER=${APP_DB_USERNAME}
      - POSTGRES_DB=${APP_DB_DBNAME} 

    # Comment out ports here if you do not want outside DB access
    ports:
      - ${APP_DB_OUT_PORT}:5432

    volumes:
      - ./db/data:/var/lib/postgresql/data/


  # WEB
  web:
    image: "dir-web:v1"
    restart: unless-stopped

    command: sh -c "poetry run python /frontend/webserver.py"

    build:
      context: ./Frontend

    networks:
      - frontend

    depends_on:
      api:
        condition: service_started
      db:
        condition: service_started

    environment:
      - API_WEB_CONNECTION_STRING=http://nginx:8000/robotic-sorter-and-packer/v1
      - APP_CONFIG=${OPERATION_MODE}
      - WEB_URL_PREFIX=${WEB_URL_PREFIX}


  # NGINX
  nginx:
    image: "dir-api:nginx"
    restart: unless-stopped

    command: sh -c "nginx -g 'daemon off;'"

    build: ./nginx

    networks:
      - backend
      - frontend

    ports:
      - ${NGINX_OUT_PORT}:8000

    depends_on:
      api:
        condition: service_started
      db:
        condition: service_started

# Create two network bridges for frontend and backend
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

